import { describe, expect, test } from "bun:test";
import { signResendPayload, verifyResendSignature } from "../../src/email/resend";

const NOW = new Date("2026-08-29T12:00:00.000Z");
const NOW_SECONDS = Math.floor(NOW.getTime() / 1000);

const BASE64_SECRET = "whsec_MfKQ9r8GKYdaOpYbCh3CZEaNkFgRwdaG";
const PLAIN_SECRET = "plain-text-secret-key";

describe("Resend / Svix webhook signature verification", () => {
  test("verifies standard Svix test vector with whsec_ base64 secret", () => {
    // Svix canonical test vector
    const svixId = "msg_p5jXN8AQM9LqvYjh3vd85xCpYUa";
    const svixTimestamp = "1614265330";
    const body = '{"test": 24322}';
    const secret = "whsec_MfKQ9r8GKYdaOpYbCh3CZEaNkFgRwdaG";
    const svixSignature = "v1,1QeggZ6nBQJWPd9P0JfKLGkmUlStWzChX5qvX3NRSns=";

    const testNow = new Date(1614265330 * 1000);
    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp,
        svixSignature,
        body,
        secret,
        now: testNow,
      }),
    ).toBe(true);
  });

  test("accepts a correctly signed delivery generated by signResendPayload", () => {
    const svixId = "msg_12345";
    const svixTimestamp = String(NOW_SECONDS);
    const body = JSON.stringify({ type: "email.bounced", data: { to: ["bounced@example.com"] } });
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp,
      body,
      secret: BASE64_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp,
        svixSignature,
        body,
        secret: BASE64_SECRET,
        now: NOW,
      }),
    ).toBe(true);
  });

  test("accepts a valid signature using a plain-text secret without whsec_ prefix", () => {
    const svixId = "msg_67890";
    const svixTimestamp = String(NOW_SECONDS);
    const body = JSON.stringify({
      type: "email.complained",
      data: { to: ["complaint@example.com"] },
    });
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp,
      body,
      secret: PLAIN_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp,
        svixSignature,
        body,
        secret: PLAIN_SECRET,
        now: NOW,
      }),
    ).toBe(true);
  });

  test("accepts delivery when svix-signature contains multiple candidate signatures", () => {
    const svixId = "msg_rotation";
    const svixTimestamp = String(NOW_SECONDS);
    const body = JSON.stringify({ type: "email.bounced", data: { to: ["user@example.com"] } });
    const validSig = signResendPayload({
      svixId,
      svixTimestamp,
      body,
      secret: BASE64_SECRET,
    });

    const svixSignature = `v1,invalidSig123 ${validSig} v2,differentVersionSignature`;

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp,
        svixSignature,
        body,
        secret: BASE64_SECRET,
        now: NOW,
      }),
    ).toBe(true);
  });

  test("accepts object body by serializing to JSON", () => {
    const svixId = "msg_object";
    const svixTimestamp = String(NOW_SECONDS);
    const payloadObject = { type: "email.bounced", data: { to: ["user@example.com"] } };
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp,
      body: payloadObject,
      secret: BASE64_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp,
        svixSignature,
        body: payloadObject,
        secret: BASE64_SECRET,
        now: NOW,
      }),
    ).toBe(true);
  });

  test("refuses signature made with a different secret", () => {
    const svixId = "msg_wrong_secret";
    const svixTimestamp = String(NOW_SECONDS);
    const body = JSON.stringify({ type: "email.bounced" });
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp,
      body,
      secret: "whsec_YW5vdGhlci1zZWNyZXQta2V5LTEyMzQ1Ng==",
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp,
        svixSignature,
        body,
        secret: BASE64_SECRET,
        now: NOW,
      }),
    ).toBe(false);
  });

  test("refuses signature with mismatched message id", () => {
    const svixTimestamp = String(NOW_SECONDS);
    const body = JSON.stringify({ type: "email.bounced" });
    const svixSignature = signResendPayload({
      svixId: "msg_original",
      svixTimestamp,
      body,
      secret: BASE64_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId: "msg_tampered",
        svixTimestamp,
        svixSignature,
        body,
        secret: BASE64_SECRET,
        now: NOW,
      }),
    ).toBe(false);
  });

  test("refuses signature with mismatched body payload", () => {
    const svixId = "msg_body_test";
    const svixTimestamp = String(NOW_SECONDS);
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp,
      body: JSON.stringify({ type: "email.bounced", data: { to: ["legit@example.com"] } }),
      secret: BASE64_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp,
        svixSignature,
        body: JSON.stringify({ type: "email.bounced", data: { to: ["forged@example.com"] } }),
        secret: BASE64_SECRET,
        now: NOW,
      }),
    ).toBe(false);
  });

  test("refuses signature with mismatched timestamp", () => {
    const svixId = "msg_ts_test";
    const body = JSON.stringify({ type: "email.bounced" });
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp: NOW_SECONDS,
      body,
      secret: BASE64_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp: String(NOW_SECONDS - 10),
        svixSignature,
        body,
        secret: BASE64_SECRET,
        now: NOW,
      }),
    ).toBe(false);
  });

  test("refuses stale delivery exceeding tolerance window", () => {
    const svixId = "msg_stale";
    const staleSeconds = NOW_SECONDS - 301; // 5 min and 1 sec ago
    const body = JSON.stringify({ type: "email.bounced" });
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp: staleSeconds,
      body,
      secret: BASE64_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp: String(staleSeconds),
        svixSignature,
        body,
        secret: BASE64_SECRET,
        toleranceSeconds: 300,
        now: NOW,
      }),
    ).toBe(false);
  });

  test("refuses future delivery exceeding tolerance window", () => {
    const svixId = "msg_future";
    const futureSeconds = NOW_SECONDS + 301;
    const body = JSON.stringify({ type: "email.bounced" });
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp: futureSeconds,
      body,
      secret: BASE64_SECRET,
    });

    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp: String(futureSeconds),
        svixSignature,
        body,
        secret: BASE64_SECRET,
        toleranceSeconds: 300,
        now: NOW,
      }),
    ).toBe(false);
  });

  test("accepts delivery within custom tolerance window", () => {
    const svixId = "msg_custom_tolerance";
    const pastSeconds = NOW_SECONDS - 50;
    const body = JSON.stringify({ type: "email.bounced" });
    const svixSignature = signResendPayload({
      svixId,
      svixTimestamp: pastSeconds,
      body,
      secret: BASE64_SECRET,
    });

    // Valid with 60s tolerance
    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp: String(pastSeconds),
        svixSignature,
        body,
        secret: BASE64_SECRET,
        toleranceSeconds: 60,
        now: NOW,
      }),
    ).toBe(true);

    // Invalid with 30s tolerance
    expect(
      verifyResendSignature({
        svixId,
        svixTimestamp: String(pastSeconds),
        svixSignature,
        body,
        secret: BASE64_SECRET,
        toleranceSeconds: 30,
        now: NOW,
      }),
    ).toBe(false);
  });

  test("refuses missing or invalid required arguments", () => {
    const validSig = signResendPayload({
      svixId: "msg_1",
      svixTimestamp: NOW_SECONDS,
      body: "{}",
      secret: BASE64_SECRET,
    });

    const cases: Array<Parameters<typeof verifyResendSignature>[0]> = [
      {
        svixId: null,
        svixTimestamp: String(NOW_SECONDS),
        svixSignature: validSig,
        body: "{}",
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "",
        svixTimestamp: String(NOW_SECONDS),
        svixSignature: validSig,
        body: "{}",
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "msg_1",
        svixTimestamp: null,
        svixSignature: validSig,
        body: "{}",
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "msg_1",
        svixTimestamp: "invalid-timestamp",
        svixSignature: validSig,
        body: "{}",
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "msg_1",
        svixTimestamp: String(NOW_SECONDS),
        svixSignature: null,
        body: "{}",
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "msg_1",
        svixTimestamp: String(NOW_SECONDS),
        svixSignature: "",
        body: "{}",
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "msg_1",
        svixTimestamp: String(NOW_SECONDS),
        svixSignature: "garbage",
        body: "{}",
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "msg_1",
        svixTimestamp: String(NOW_SECONDS),
        svixSignature: validSig,
        body: null,
        secret: BASE64_SECRET,
        now: NOW,
      },
      {
        svixId: "msg_1",
        svixTimestamp: String(NOW_SECONDS),
        svixSignature: validSig,
        body: "{}",
        secret: "",
        now: NOW,
      },
    ];

    for (const testCase of cases) {
      expect(verifyResendSignature(testCase)).toBe(false);
    }
  });
});
